version: 1.8.0.{build}

only_commits:
  files:
    - 'src/'
    - 'test/'

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Install-Module Pester -MinimumVersion 3.4.0 -Scope CurrentUser -Force
      Install-Module psake -Scope CurrentUser -Force
      Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
      Install-Module platyPS -Scope CurrentUser -Force

build: off

test_script:
    - ps: |
        $testResultsFile = ".\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) {
            throw "$($res.FailedCount) tests failed."
        }