version: 1.8.0.{build}

only_commits:
  files:
    - 'src/'

install:
  - ps: |
      Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      Install-Module Pester -MinimumVersion 3.4.0 -Scope CurrentUser -Force
      Install-Module psake -Scope CurrentUser -Force
      Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
      Install-Module platyPS -Scope CurrentUser -Force

build: off

test_script:
    - ps: Invoke-Pester -Path .\test